<?php #namespace Game\Utils;
	define('INIT_HOOMAN_STRENGTH', 5);
	define('INIT_HOOMAN_AGILITY', 5);
	define('INIT_DWARF_STRENGTH', 7);
	define('INIT_DWARF_AGILITY', 3);
	define('INIT_ELF_STRENGTH', 3);
	define('INIT_ELF_AGILITY', 7);
	define('INIT_SWORD_STRENGTH', 3);
	define('INIT_SWORD_AGILITY', 3);
	define('INIT_AXE_STRENGTH', 5);
	define('INIT_AXE_AGILITY', 1);
	define('INIT_BOW_STRENGTH', 2);
	define('INIT_BOW_AGILITY', 4);